### ISSUE TITLE
[SyntaxError: Unexpected end of input] error 

### ISSUE THREAD

**Issue by abdrakhimov** [signalfx/fetch-swagger-schema#3]
Hello. I get the following error everytime i execute fetch-swagger-schema http://petstore.swagger.wordnik.com/api/api-docs pets.json
[SyntaxError: Unexpected end of input] error 
Thanx

**Comment by beau6183** [comment]
I'm getting [SyntaxError: Unexpected token <]

**Comment by okigan** [comment]
+1

**Comment by okigan** [comment]
my api server requires authentication which leads to this problem (there could be other causes).

temporary turning authentication off resolves the problem for me (obviously this will not work for everybody)

**Comment by oztu** [comment]
I believe this is occurring because that url no longer exists (not that Swagger has moved to 2.0, I think the 1.2 sample resources have been turned off). So this seems to be more of the example in the README broken than anything else. I'll try to find another instance of the petstore schema or just set one up myself if I can't.

**Comment by OwenBrotherwood** [comment]
Using the v2 swagger.json ...
fetch-swagger-schema http://petstore.swagger.io/v2/swagger.json
[TypeError: Cannot read property 'length' of undefined]

**Comment by oztu** [comment]
Unfortunately this tool was designed for 1.2, I haven't taken a look at the v2 docs to see if this sort of tool is even useful for the new spec. The old spec broke apart resource listing and definition -- this tool basically compiles all of that to one file.

**Comment by FedeG** [comment]
@OwenBrotherwood in Swagger v2 already has all the information in swagger.json.

(More information in https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide)

**Comment by adborden** [comment]
I don't think this is related to Swagger 2.0, I'm still getting it with v0.1.2 and on master. I think it's a race condition, parsing the data buffer before the stream is actually done. Should I open a new issue?

**Comment by OwenBrotherwood** [comment]
@adborden Go for it: if you think you are onto something, it is good to get it looked at and possibly fixed
